# test using amtool: docker run -it --entrypoint=sh prom/alertmanager:latest
route:
  receiver: 'discord'
  repeat_interval: 3h #3h
  group_interval: 10m #5m
  group_wait: 5m #1m
  routes:
  - receiver: 'discord'

receivers:
- name: 'discord'
  webhook_configs:
  - url: 'http://alertmanager-discord:9094'
    send_resolved: true
