# test using amtool: docker run -it --entrypoint=sh prom/alertmanager:latest
route:
  receiver: 'logstash'
  repeat_interval: 3h #3h
  group_interval: 5m #5m
  group_wait: 1m #1m
  routes:
  - receiver: 'logstash'
    continue: true
  - receiver: 'discord'

receivers:
- name: 'discord'
  webhook_configs:
  - url: 'http://alertmanager-discord:9094'
- name: 'logstash'
  webhook_configs:
  # Whether or not to notify about resolved alerts.
  - send_resolved: true
    url: "http://logstash:8080/"
  
