groups:
- name: alert.rules_container-groups
  rules:
  - alert: monitoring_container_group_missing_members
    expr: count by(container_group, host) (rate(container_last_seen{container_group=~"monitoring",name=~".+"}[5m]))
      < 10
    for: 5m
    annotations:
      description: '{{ $labels.container_group }} is missing containers. Container
        count is {{ $value }}/13.'
      summary: 'CONTAINER GROUP WARNING: CONTAINER GROUP ''{{ $labels.container_group
        }}'' on ''{{ $labels.host }}'''
