version: '2.1'


services:

  master-nodeexporter:
    extends:
      file: docker-compose.yml
      service: master-nodeexporter

  master-cadvisor:
    extends:
      file: docker-compose.yml
      service: master-cadvisor

  prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus
    networks:
      - default 
      - reverse-proxy
    volumes:
      - prometheus_storage:/data
    environment:
      - VIRTUAL_HOST=prometheus.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=prometheus.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
        
  blackboxprober:
    extends:
      file: docker-compose.yml
      service: blackboxprober
 
  snmpexporter:
    extends:
      file: docker-compose.yml
      service: snmpexporter
        
  grafana:
    extends:
      file: docker-compose.yml
      service: grafana
    volumes:
      - grafana_config:/etc/grafana
      - grafana_storage:/var/lib/grafana
    networks:
      - default
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=dashboard.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=dashboard.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
      
  alertmanager:
    extends:
      file: docker-compose.yml
      service: alertmanager
    networks:
      - default
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=alertmanager.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=alertmanager.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
        
  alertmanager-discord:
    extends: 
      file: docker-compose.yml
      service: alertmanager-discord
    environment:
      - DISCORD_WEBHOOK=${ALERTMANAGER_DISCORD_WEBHOOK:-SUBFAIL}

networks:
  default:
    external:
      name: monitoring_logging
  reverse-proxy:
    external:
      name: reverse-proxy

volumes:
  prometheus_storage:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/prometheus/storage"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  grafana_storage:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/grafana/storage"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  grafana_config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/grafana/config"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
