version: '2.1'


services:

#########################################################
####                   MONITORING                    ####
#########################################################

  # Runs on your node(s) and forwards node(host) metrics to Prometheus.
  master-nodeexporter:
    cap_add:
      - SYS_TIME
    image: prom/node-exporter:v0.17.0
    expose:
      - 9100
    restart: always
    labels:
      container_group: monitoring
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group

#########################################################

  # Runs on your node(s) and forwards container metrics to Prometheus.
  master-cadvisor:
    image: google/cadvisor:v0.32.0   #v0.25.0
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    labels:
      container_group: monitoring
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group

#########################################################

  # Storage and search backend. Gets all metrics from cAdvisor and Nodeexporter and is the backend that Grafana runs on.
  prometheus:
    image: prom/prometheus:v2.6.0   #v1.7.1
    expose:
      - 9090
    volumes:
      - ../storage/prometheus:/data
      - ./prometheus:/etc/prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/data"
      - "--web.listen-address=:9090"
      - "--storage.tsdb.retention=90d"
    labels:
      container_group: monitoring
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group

#########################################################

  # Pretty frontend to explore and check out all your metrics.
  grafana:
    image: grafana/grafana:5.4.2   #5.2.2
    expose:
      - 3000
#    volumes:
#      - ../storage/grafana:/var/lib/grafana
    restart: always
    user: "104"
    labels:
      container_group: monitoring
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin

#########################################################

  # Alerting plugin wrapping Prometheus and taking care of your metric alerting needs.
  alertmanager:
    image: prom/alertmanager:v0.8.0
    expose:
      - 9093
    restart: always
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - ../storage/alertmanager/:/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    labels:
      container_group: monitoring
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group

#########################################################
  blackboxprober:
    image: prom/blackbox-exporter:v0.13.0   #v0.10.0
    cap_add:
      - NET_RAW
    volumes:
      - ./blackboxprober:/etc/blackbox_exporter
    ports:
      - 9115:9115
    restart: always
    labels:
      container_group: monitoring
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group

  snmpexporter:
    image: prom/snmp-exporter:v0.14.0
    volumes:
      - ./snmpexporter:/etc/snmp_exporter/
    ports:
      - 9116:9116
    restart: always
    labels:
      container_group: monitoring
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group

  # Alertmanager messages to discord
  alertmanager-discord:
    image: funkypenguin/alertmanager-discord
    expose:
      - 9094
    restart: always
    labels:
      container_group: monitoring
    environment:
      - DISCORD_WEBHOOK=${ALERTMANAGER_DISCORD_WEBHOOK:-SUBFAIL} 
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL} 
        labels: container_group

#########################################################
####                   Networking                    ####
#########################################################

# Extra-network is necessary to have a dedicated IP for Logstash to forwards log to.
networks:
  default:
    external:
      name: monitoring_logging

#########################################################

  #### Other tools to look into:
  # topbeat (Metrics for ELK):
  # collectd (Alternative for metric collection on nodes):

