filebeat.modules:
- module: system
  # system logs
  syslog:
    enabled: true
    var.paths:
     - /host-logs/*
     - /containerlogs/*/*
  # Authorization logs
  auth:
    enabled: true
    #var.paths: [/host-logs/*]

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~
- add_host_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  
setup.kibana.host: kibana:5601
setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
setup.dashboards.retry.interval: 1m
setup.dashboards.retry.maximum: 0


